### ISSUE TITLE
What to do with file permissions?

### ISSUE THREAD

**Issue by donno2048** [donno2048/restricted-functions#17]
What about `os.chmod` and `pathlib.Path.chmod`?

**Comment by iam-py-test** [comment]
> What about `os.chmod` and `pathlib.Path.chmod`?

As stated in #16, maybe we should add an option for it.
I am a bit busy at the moment, so give me a bit of time & I can make a PR for it.
Edit: How did you map this repo's docs to `http://restricted-functions.tk/`? That looks really cool, but it would be nice if it supported HTTPS.  When should we add the `help` command?

**Comment by donno2048** [comment]
> > What about `os.chmod` and `pathlib.Path.chmod`?
> 
> As stated in #16, maybe we should add an option for it.
> I am a bit busy at the moment, so give me a bit of time & I can make a PR for it.

Sure

> Edit: How did you map this repo's docs to `http://restricted-functions.tk/`? That looks really cool, but it would be nice if it supported HTTPS.

I used the _config file to "turn" the markdown into plain HTML, deployed it using Github pages, and finally used a kind of redirect to render it in the main webpage, and, no, unfortunately, it won't support HTTPS...

> When should we add the `help` command?

It already implemented; this is what docstrings are meant for...
